/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(group="org.immutables", name="value",version="2.7.1")
    implementation(group="org.apache.logging.log4j", name="log4j-api", version="2.4.1")
    implementation(group="org.apache.logging.log4j", name="log4j-core", version="2.4.1")
    implementation(group="org.apache.commons", name="commons-lang3", version="3.4")
    implementation(group="org.apache.commons", name="commons-csv", version="1.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("us.sodiumlabs.xmas.XmasHats")
}

